### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by faissaloo** [turbanoff/j2me-2048#2]

**Comment by turbanoff** [comment]
I used NetBeans IDE. It has Java2ME integration.
https://netbeans.org/downloads/8.2/

**Comment by faissaloo** [comment]
It doesn't register as a netbeans project for me for some reason? Also how did you get the Java2ME integration working, could you recommend an up to date tutorial? What OS are you using?  
Really appreciate *any* help with this.

**Comment by turbanoff** [comment]
I think I used this tutorial
https://netbeans.org/kb/73/javame/quickstart.html

>It doesn't register as a netbeans project for me for some reason?

Just create new project and copy source files to it.
